# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "Making-it-work" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies backend
      run: dotnet restore Backend/Backend.sln
    - name: Restore dependencies frontend
      run: dotnet restore FrontEnd/FrontEnd.sln
    - name: Build backend
      run: dotnet build Backend.sln --no-restore
    - name: Build frontend
      run: dotnet build FrontEnd.sln --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
